admin_panel_users:
     path:  /utilisateurs
     defaults: { _controller: OmaracujaAdminBundle:Admin:userPanel }
     
admin_user_activate:
     pattern: /activate/{userId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:userActivate }
     
admin_user_desactivate:
     pattern: /desactivate/{userId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:userDesactivate }

     
     
admin_panel_presentation:
     path:  /presentation
     defaults: { _controller: OmaracujaAdminBundle:Admin:presentationPanel }     
     
admin_new_presentation:
     path:  /presentation/nouvelle-page
     defaults: { _controller: OmaracujaAdminBundle:Admin:presentationNew }
     
admin_create_presentation:
     path:  /presentation/creation-page
     defaults: { _controller: OmaracujaAdminBundle:Admin:presentationCreate }


admin_panel_event:
     path:  /evenements
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventPanel } 
     
admin_events_passed:
     path:  /evenements-passes
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventsPastPanel } 
     
admin_create_event:
     path:  /creationEvenement
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventCreate }     
     
admin_event_edit:
     path:  /editionEvenement/{eventId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventEdit }
     
admin_event_picture_upload:
     path:  /evenementTelechargement/{eventId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventPictureUpload }