#USERS

admin_panel_users:
     path:  /utilisateurs/{selectedUser}
     defaults: { _controller: OmaracujaAdminBundle:Admin:userPanel, selectedUser: -1 }
     
admin_user_activate:
     pattern: /activate/{userId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:userActivate }
     
admin_user_desactivate:
     pattern: /desactivate/{userId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:userDesactivate }

#VIDEO
admin_panel_video:
     pattern: /videos
     defaults: { _controller: OmaracujaAdminBundle:Admin:videos }
     
admin_panel_videos_add:
    pattern: /ajouter-video
    defaults: { _controller: OmaracujaAdminBundle:Admin:videoCreate }    
     
admin_panel_videos_remove:
    pattern: /supprimer-video/{idVideo}
    defaults: { _controller: OmaracujaAdminBundle:Admin:videoDelete }  
    
#EVENTS  
admin_panel_event:
     path:  /evenements
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventPanel }    
     
admin_events_passed:
     path:  /evenements-passes
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventsPastPanel } 
     
admin_create_event:
     path:  /creationEvenement
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventCreate }     
     
admin_event_edit:
     path:  /editionEvenement/{eventId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventEdit }
     
admin_event_picture_upload:
     path:  /evenementTelechargement/{eventId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventPictureUpload }
    
     
#ALBUM
admin_add_event_album:
     path:  /ajouterEvenementAlbum/{eventId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:addAlbumEvent }
    

admin_edit_event_album:
     path:  /editionAlbum/{albumId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:editAlbumEvent }     
     
admin_remove_album:
     path:  /albums/remove/{albumId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:removeAlbumEvent }   
     
#PHOTOS         
admin_panel_albums:
     path:  /albums/{mois}
     defaults: { _controller: OmaracujaAdminBundle:Admin:albumsPanel, mois: now }   
     
     
     
admin_picture_upload:
     path:  /photoTelechargement/{albumId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:pictureUpload }
     
admin_picture_remove:
     path:  /photoSupression/{idPicture}
     defaults: { _controller: OmaracujaAdminBundle:Admin:pictureRemove }
     
     
#NEWLETTERS

admin_panel_newsletter:
     path:  /newsletter/create
     defaults: { _controller: OmaracujaAdminBundle:Admin:newsletterCreatePanel} 
