#USERS

admin_panel_users:
     path:  /utilisateurs
     defaults: { _controller: OmaracujaAdminBundle:Admin:userPanel }
     
admin_user_activate:
     pattern: /activate/{userId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:userActivate }
     
admin_user_desactivate:
     pattern: /desactivate/{userId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:userDesactivate }

     
#PRESENTATION  
admin_panel_presentation:
     path:  /presentation
     defaults: { _controller: OmaracujaAdminBundle:Admin:presentationPanel }     
     
admin_new_presentation:
     path:  /presentation/nouvelle-page
     defaults: { _controller: OmaracujaAdminBundle:Admin:presentationNew }
     
admin_create_presentation:
     path:  /presentation/creation-page
     defaults: { _controller: OmaracujaAdminBundle:Admin:presentationCreate }


#EVENTS  
admin_panel_event:
     path:  /evenements
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventPanel } 
     
admin_events_passed:
     path:  /evenements-passes
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventsPastPanel } 
     
admin_create_event:
     path:  /creationEvenement
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventCreate }     
     
admin_event_edit:
     path:  /editionEvenement/{eventId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventEdit }
     
admin_event_picture_upload:
     path:  /evenementTelechargement/{eventId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:eventPictureUpload }
    
     
#ALBUM
admin_add_event_album:
     path:  /ajouterEvenementAlbum/{eventId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:addAlbumEvent }
    

admin_edit_event_album:
     path:  /EditionAlbum/{albumId}
     defaults: { _controller: OmaracujaAdminBundle:Admin:editAlbumEvent }     
     
     
#PHOTOS         
admin_panel_pictures:
     path:  /photos/{mois}
     defaults: { _controller: OmaracujaAdminBundle:Admin:picturePanel, mois: now }   
     
     
admin_picture_upload:
     path:  /photoTelechargement
     defaults: { _controller: OmaracujaAdminBundle:Admin:pictureUpload }
