# app/config/routing.yml

omaracuja_construction:
    pattern:  /
    defaults: { _controller: OmaracujaFrontBundle:Construction:construction }
    requirements:
        _method:  GET

omaracuja_front:
    resource: "@OmaracujaFrontBundle/Resources/config/routing.yml"
    prefix:   /test        
          
        
user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /test
    
fuser_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /test/profile
    
user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /test/register
    
user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /test/resetting
    
user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /test/profile

