# app/config/routing.yml

omaracuja_construction:
    pattern:  /
    defaults: { _controller: OmaracujaFrontBundle:Construction:construction }
    requirements:
        _method:  GET

omaracuja_front:
    resource: "@OmaracujaFrontBundle/Resources/config/routing.yml"
    prefix:   /test        
          
omaracuja_admin:
    resource: "@OmaracujaAdminBundle/Resources/config/routing.yml"
    prefix:   /test/admin          
          

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /test

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /test/compte
    
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /test/inscription
    
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /test/resetting
    
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /test/compte

