security:
    encoders:
        Omaracuja\UserBundle\Entity\User: sha512
        Omaracuja\UserBundle\Entity\Group: sha512
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      fos_userbundle:
          id: fos_user.user_manager
      in_memory:          
          memory:
              users:
                  mathurin:  { password: rogerrabbit, roles: [ 'ROLE_USER' ] }
                  admin: { password: rogerrabbit, roles: [ 'ROLE_ADMIN' ] }

    firewalls:      
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|media)/
            security: false
        main:
            pattern:        ^/
            anonymous:      true
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path: /accueil 
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /accueil
            remember_me:
                key:        %secret%

    access_control:
         - { path: ^/construction$,    role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/,    role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/compte/login$,    role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/compte/register,  role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/compte,          role: [ROLE_USER, ROLE_ADMIN] }    
         - { path: ^/admin/,          role: [ROLE_ADMIN] }    