   
front_presentation:
     path:  /presentation
     defaults: { _controller: OmaracujaFrontBundle:Front:presentation }
     
front_blog_post_create:
     path:  /blogPostCreate
     defaults: { _controller: OmaracujaFrontBundle:Front:blogPostCreate }
     
front_evennement:
     path:  /evennements
     defaults: { _controller: OmaracujaFrontBundle:Front:evennement }    
     
front_evennement_past:
     path:  /evennements-passes
     defaults: { _controller: OmaracujaFrontBundle:Front:evennementPast }
     
front_picture_download:
     path:  /photos/telechargement/{idPicture}
     defaults: { _controller: OmaracujaFrontBundle:Front:downloadPicture }
     
front_albums:
     path:  /photos/{mois}
     defaults: { _controller: OmaracujaFrontBundle:Front:albums, mois: now } 
     
front_album:
     path:  /album/{albumId}
     defaults: { _controller: OmaracujaFrontBundle:Front:album }

front_video:
     path:  /videos
     defaults: { _controller: OmaracujaFrontBundle:Front:videos }
     
front_contact:
     path:  /contact
     defaults: { _controller: OmaracujaFrontBundle:Front:contact }
     