#front_accueil:
#     path:  /accueil
#     defaults: { _controller: OmaracujaFrontBundle:Front:accueil }
     
front_presentation:
     path:  /presentation
     defaults: { _controller: OmaracujaFrontBundle:Front:presentation }
     
front_blog_post_create:
     path:  /blogPostCreate
     defaults: { _controller: OmaracujaFrontBundle:Front:blogPostCreate }
     
front_evennement:
     path:  /evennements
     defaults: { _controller: OmaracujaFrontBundle:Front:evennement }    
     
front_evennement_past:
     path:  /evennements-passes
     defaults: { _controller: OmaracujaFrontBundle:Front:evennementPast }
     
front_picture_download:
     path:  /photos/telechargement/{idPicture}
     defaults: { _controller: OmaracujaFrontBundle:Front:downloadPicture }
     
front_pictures:
     path:  /photos/{mois}
     defaults: { _controller: OmaracujaFrontBundle:Front:pictures, mois: now }   
     