fos_user_security:
    resource: "routing/security.xml"
    
fos_user_profile:
    resource: "routing/compte.xml"
    prefix: /compte
    
fos_user_registration_register:
    resource: "routing/inscription.xml"
    prefix: /inscription
    
fos_user_resetting:
    resource: "routing/resetting.xml"
    prefix: /resetting
    
fos_user_change_password:
    resource: "change_mot_de_passe.xml"
    prefix: /compte